require "test_helper"

# The standalone one-pagers go to clients — emailed as a file, or opened from a
# link. A page with the browser's blank document icon in the tab reads as
# unfinished, and nothing else in the app would notice: these files are
# generated by a script outside the repo, so a rebuild that lost the tag would
# ship silently.
class OnePagerFaviconTest < ActiveSupport::TestCase
  SELF_CONTAINED = %w[ vertonow.html verto-for-research.html ].freeze

  test "each one-pager carries the app's own mark, inline" do
    mark = Rails.root.join("app/assets/images/favicon.svg").read
    expected = Base64.strict_encode64(mark)

    SELF_CONTAINED.each do |name|
      html = Rails.root.join("public", name).read
      link = html[/<link[^>]*rel="icon"[^>]*>/]
      assert link, "#{name} declares no favicon"

      # A data: URI specifically. These files are opened from disk as often as
      # over HTTP, and a downloaded copy has no host to fetch /favicon.svg from.
      assert_match %r{href="data:image/svg\+xml;base64,}, link,
        "#{name}'s favicon must be inline — a downloaded copy can't resolve a path"
      assert_includes link, expected,
        "#{name}'s favicon isn't app/assets/images/favicon.svg — the app and the " \
        "one-pagers have drifted apart"
    end
  end
end
