require "test_helper"

# public/webflow is a handover kit: the research one-pager stripped into pieces
# that paste into Webflow. Its constraints aren't enforced by anything Webflow
# tells you at paste time — an over-length field is silently truncated, and a
# leftover placeholder is a broken image on a client-facing page. They're cheap
# to pin here, and the kit is regenerated by hand (build_webflow.py), which is
# exactly when they'd be broken.
class WebflowKitTest < ActiveSupport::TestCase
  KIT = Rails.root.join("public", "webflow")

  # Webflow caps an HTML Embed element and each page custom-code field at
  # 10,000 characters. The whole reason the demo is split across three files is
  # to stay under it.
  LIMIT = 10_000

  PASTE_FILES = %w[
    webflow-1-head-css.html webflow-2-embed-markup.html webflow-3-body-js.html
    paste-1-head.html paste-2-body.html paste-3-footer.html
  ].freeze

  test "every paste file fits in a Webflow field" do
    PASTE_FILES.each do |name|
      size = KIT.join(name).size
      assert_operator size, :<=, LIMIT,
        "#{name} is #{size} chars — Webflow truncates past #{LIMIT}, silently"
    end
  end

  test "the fast path resolves its own assets" do
    body = KIT.join("paste-2-body.html").read
    assert_no_match(/ASSET_BASE/, body,
      "the fast path is meant to be pasted as-is: a placeholder here is a broken image")
    assert_match %r{https://app\.playverto\.com/webflow/assets/[\w-]+\.webp}, body,
      "images must be absolute — a Webflow page can't resolve a relative path into this app"
    KIT.join("paste-2-body.html").read.scan(%r{/webflow/assets/([\w-]+\.webp)}).flatten.uniq.each do |asset|
      assert KIT.join("assets", asset).exist?, "paste-2 references assets/#{asset}, which isn't in the kit"
    end
  end

  test "the kit carries no client's name" do
    # It was a proposal addressed to one firm; these files are the public page.
    %w[index.html paste-2-body.html webflow-2-embed-markup.html styles.css].each do |name|
      assert_no_match(/Strategic Analytics/, KIT.join(name).read, "#{name} still names the client")
    end
  end

  test "the stylesheet defaults to light, with no theme attribute to set it" do
    # A Webflow page's body has no data-theme, so a palette that lives behind
    # one renders as whatever :root happens to be — which shipped as dark once.
    css = KIT.join("styles.css").read
    assert_no_match(/data-theme/, css, "a theme-qualified rule can't apply on a Webflow page")
    assert_match(/:root\{[^}]*--bg:\s*#ffffff/m, css, "the default palette isn't the light one")
  end
end
