// The emoji set behind the editor's emoji picker.
//
// Two tiers, because browsing and searching want opposite things.
//
// EMOJI_CATEGORIES is the CURATED set — the ~130 that actually turn up in
// survey answers, grouped so a creator can scan a category instead of hunting.
// This is what the tabs render, and it is deliberately small: a browse grid of
// a thousand icons buries the ones anyone picks.
//
// UNICODE_EMOJI is the FULL set — every emoji-presentation character worth
// offering, ~1,400 of them, with search terms taken from their Unicode names.
// It is never rendered as a grid; it only widens what SEARCH can find. Before
// it, search looked at hand-written terms only, so anything nobody had thought
// to describe was unfindable — "the emoji library doesnt feel exhaustive / as
// big as you get on phones. Would be good if we can access the fullest library
// possible when searching" (18 Aug).
//
// Adding a curated one: put it in the category it belongs to, and give it search
// terms a creator would actually type. The Unicode tier needs no maintenance.

export const EMOJI_CATEGORIES = [
  {
    key: "faces",
    label: "Faces",
    emoji: [
      [ "🙂", "happy smile pleased good" ],
      [ "😀", "grin happy" ],
      [ "😍", "love heart eyes adore" ],
      [ "🤩", "star struck amazed excited" ],
      [ "😌", "relieved calm content" ],
      [ "😐", "neutral meh ok" ],
      [ "🙁", "sad unhappy frown" ],
      [ "😟", "worried concerned" ],
      [ "😨", "scared afraid fear unsafe" ],
      [ "😰", "anxious stress worried sweat" ],
      [ "😢", "cry sad tear" ],
      [ "😡", "angry mad furious" ],
      [ "🤔", "thinking unsure maybe hmm" ],
      [ "😴", "sleep tired rest" ],
      [ "🤐", "quiet silent prefer not to say" ],
      [ "🥳", "party celebrate" ],
      [ "😎", "cool confident" ],
      [ "🫤", "unsure meh uncertain" ]
    ]
  },
  {
    key: "people",
    label: "People",
    emoji: [
      [ "👍", "yes agree thumbs up good" ],
      [ "👎", "no disagree thumbs down bad" ],
      [ "👋", "wave hello hi" ],
      [ "🙌", "celebrate praise yay" ],
      [ "👏", "clap applause well done" ],
      [ "🤝", "handshake deal partner agree" ],
      [ "💪", "strong strength fitness muscle" ],
      [ "🧠", "brain mental health mind think" ],
      [ "👀", "eyes watch look" ],
      [ "👨‍👩‍👧", "family parents children" ],
      [ "🫂", "hug friends support together" ],
      [ "👶", "baby child infant" ],
      [ "🧑", "person adult someone" ],
      [ "👴", "older elderly senior" ],
      [ "👮", "police officer patrol safety" ],
      [ "👩‍⚕️", "doctor nurse health medical" ],
      [ "👨‍🏫", "teacher school education" ],
      [ "🧑‍💻", "work computer developer office" ]
    ]
  },
  {
    key: "money",
    label: "Money & work",
    emoji: [
      [ "💷", "pound money salary income" ],
      [ "💰", "money bag savings wealth" ],
      [ "💳", "card debt credit payment" ],
      [ "🏦", "bank savings account" ],
      [ "📈", "up growth investment increase" ],
      [ "📉", "down decrease loss unemployment" ],
      [ "🧾", "bill receipt cost expenses" ],
      [ "🧮", "budget calculate abacus" ],
      [ "💼", "work job briefcase business" ],
      [ "🚀", "launch startup business grow" ],
      [ "🏢", "office building company" ],
      [ "🛒", "shopping groceries buy" ],
      [ "🏷️", "price tag discount" ],
      [ "⏰", "time hours deadline" ],
      [ "📊", "chart data results" ],
      [ "🤑", "rich money profit" ]
    ]
  },
  {
    key: "health",
    label: "Health & life",
    emoji: [
      [ "❤️", "heart love health" ],
      [ "🩺", "doctor health check medical" ],
      [ "🏥", "hospital healthcare" ],
      [ "💊", "medicine pills treatment" ],
      [ "🏃", "run exercise fitness active" ],
      [ "🚴", "cycle bike exercise" ],
      [ "🧘", "calm yoga meditation wellbeing" ],
      [ "🥗", "salad diet healthy food" ],
      [ "🍽️", "food meal eat dinner" ],
      [ "🥤", "drink water hydration" ],
      [ "🛌", "sleep bed rest" ],
      [ "🌱", "growth wellbeing plant new" ],
      [ "🚭", "no smoking quit" ],
      [ "🧴", "care hygiene wash" ],
      [ "🦷", "dental teeth" ],
      [ "🧑‍🦽", "accessibility disability wheelchair" ]
    ]
  },
  {
    key: "places",
    label: "Places & travel",
    emoji: [
      [ "🏠", "home house housing" ],
      [ "🏘️", "neighbourhood community houses" ],
      [ "🏫", "school college education" ],
      [ "🎓", "graduate university degree" ],
      [ "🏛️", "government council civic" ],
      [ "⛪", "church faith religion" ],
      [ "🏪", "shop store local" ],
      [ "🌳", "park tree green space nature" ],
      [ "🌍", "world environment climate earth" ],
      [ "🚌", "bus public transport" ],
      [ "🚗", "car drive vehicle" ],
      [ "🚲", "bicycle bike cycling" ],
      [ "🚶", "walk walking pedestrian" ],
      [ "✈️", "plane travel flight holiday" ],
      [ "🚉", "train station rail" ],
      [ "🛣️", "road street highway" ],
      [ "💡", "light lighting idea street lamp" ],
      [ "🚨", "alarm crime emergency police" ]
    ]
  },
  {
    key: "objects",
    label: "Things",
    emoji: [
      [ "📱", "phone mobile device" ],
      [ "💻", "laptop computer online" ],
      [ "📚", "books study reading learning" ],
      [ "✏️", "write pencil other edit" ],
      [ "📝", "note form survey write" ],
      [ "📅", "calendar date weekly daily" ],
      [ "🗓️", "calendar monthly schedule" ],
      [ "🔑", "key rent access" ],
      [ "🛡️", "shield safety protection secure" ],
      [ "🔧", "tool repair fix trade" ],
      [ "🧹", "clean cleaning tidy streets" ],
      [ "🎪", "event festival community fun" ],
      [ "🎁", "gift reward prize" ],
      [ "📢", "announce voice speak loud" ],
      [ "🔔", "bell notify reminder" ],
      [ "🗑️", "bin waste rubbish" ],
      [ "♻️", "recycle sustainable green" ],
      [ "🔋", "battery energy power" ]
    ]
  },
  {
    key: "symbols",
    label: "Symbols",
    emoji: [
      [ "✅", "yes tick check done correct" ],
      [ "❌", "no cross wrong incorrect" ],
      [ "⭐", "star favourite rating best" ],
      [ "🚫", "none never forbidden no" ],
      [ "⚠️", "warning caution risk" ],
      [ "❓", "question unknown unsure" ],
      [ "❗", "important urgent" ],
      [ "➕", "plus add more" ],
      [ "➖", "minus less fewer" ],
      [ "🔁", "repeat sometimes often again" ],
      [ "♾️", "always infinite forever" ],
      [ "🌙", "night rarely moon evening" ],
      [ "☀️", "day sun morning" ],
      [ "🔷", "blue diamond shape" ],
      [ "🔶", "orange diamond shape" ],
      [ "🟢", "green circle good go" ],
      [ "🟡", "yellow circle medium" ],
      [ "🔴", "red circle stop bad" ],
      [ "🟣", "purple circle" ],
      [ "🥇", "first gold best rank" ],
      [ "🥈", "second silver rank" ],
      [ "🥉", "third bronze rank" ],
      [ "💯", "hundred perfect full" ],
      [ "🔥", "fire hot popular trending" ]
    ]
  }
]


// The full searchable tier: [emoji, terms-from-its-Unicode-name]. Generated
// from the Unicode data rather than hand-written, which is the point — nobody
// has to have anticipated the word a creator types.
export const UNICODE_EMOJI = [
  [ "🌀", "cyclone" ],
  [ "🌁", "foggy" ],
  [ "🌂", "closed umbrella" ],
  [ "🌃", "night stars" ],
  [ "🌄", "sunrise over mountains" ],
  [ "🌅", "sunrise" ],
  [ "🌆", "cityscape at dusk" ],
  [ "🌇", "sunset over buildings" ],
  [ "🌈", "rainbow" ],
  [ "🌉", "bridge at night" ],
  [ "🌊", "water wave" ],
  [ "🌋", "volcano" ],
  [ "🌌", "milky way" ],
  [ "🌍", "earth globe europe africa" ],
  [ "🌎", "earth globe americas" ],
  [ "🌏", "earth globe asia australia" ],
  [ "🌐", "globe meridians" ],
  [ "🌑", "new moon" ],
  [ "🌒", "waxing crescent moon" ],
  [ "🌓", "first quarter moon" ],
  [ "🌔", "waxing gibbous moon" ],
  [ "🌕", "full moon" ],
  [ "🌖", "waning gibbous moon" ],
  [ "🌗", "last quarter moon" ],
  [ "🌘", "waning crescent moon" ],
  [ "🌙", "crescent moon" ],
  [ "🌚", "new moon" ],
  [ "🌛", "first quarter moon" ],
  [ "🌜", "last quarter moon" ],
  [ "🌝", "full moon" ],
  [ "🌞", "sun" ],
  [ "🌟", "glowing star" ],
  [ "🌠", "shooting star" ],
  [ "🌡", "thermometer" ],
  [ "🌢", "black droplet" ],
  [ "🌣", "white sun" ],
  [ "🌤", "white sun small cloud" ],
  [ "🌥", "white sun behind cloud" ],
  [ "🌦", "white sun behind cloud rain" ],
  [ "🌧", "cloud rain" ],
  [ "🌨", "cloud snow" ],
  [ "🌩", "cloud lightning" ],
  [ "🌪", "cloud tornado" ],
  [ "🌫", "fog" ],
  [ "🌬", "wind blowing" ],
  [ "🌭", "hot dog" ],
  [ "🌮", "taco" ],
  [ "🌯", "burrito" ],
  [ "🌰", "chestnut" ],
  [ "🌱", "seedling" ],
  [ "🌲", "evergreen tree" ],
  [ "🌳", "deciduous tree" ],
  [ "🌴", "palm tree" ],
  [ "🌵", "cactus" ],
  [ "🌶", "hot pepper" ],
  [ "🌷", "tulip" ],
  [ "🌸", "cherry blossom" ],
  [ "🌹", "rose" ],
  [ "🌺", "hibiscus" ],
  [ "🌻", "sunflower" ],
  [ "🌼", "blossom" ],
  [ "🌽", "ear maize" ],
  [ "🌾", "ear rice" ],
  [ "🌿", "herb" ],
  [ "🍀", "four leaf clover" ],
  [ "🍁", "maple leaf" ],
  [ "🍂", "fallen leaf" ],
  [ "🍃", "leaf fluttering in wind" ],
  [ "🍄", "mushroom" ],
  [ "🍅", "tomato" ],
  [ "🍆", "aubergine" ],
  [ "🍇", "grapes" ],
  [ "🍈", "melon" ],
  [ "🍉", "watermelon" ],
  [ "🍊", "tangerine" ],
  [ "🍋", "lemon" ],
  [ "🍌", "banana" ],
  [ "🍍", "pineapple" ],
  [ "🍎", "red apple" ],
  [ "🍏", "green apple" ],
  [ "🍐", "pear" ],
  [ "🍑", "peach" ],
  [ "🍒", "cherries" ],
  [ "🍓", "strawberry" ],
  [ "🍔", "hamburger" ],
  [ "🍕", "slice pizza" ],
  [ "🍖", "meat on bone" ],
  [ "🍗", "poultry leg" ],
  [ "🍘", "rice cracker" ],
  [ "🍙", "rice ball" ],
  [ "🍚", "cooked rice" ],
  [ "🍛", "curry rice" ],
  [ "🍜", "steaming bowl" ],
  [ "🍝", "spaghetti" ],
  [ "🍞", "bread" ],
  [ "🍟", "french fries" ],
  [ "🍠", "roasted sweet potato" ],
  [ "🍡", "dango" ],
  [ "🍢", "oden" ],
  [ "🍣", "sushi" ],
  [ "🍤", "fried shrimp" ],
  [ "🍥", "fish cake swirl design" ],
  [ "🍦", "soft ice cream" ],
  [ "🍧", "shaved ice" ],
  [ "🍨", "ice cream" ],
  [ "🍩", "doughnut" ],
  [ "🍪", "cookie" ],
  [ "🍫", "chocolate bar" ],
  [ "🍬", "candy" ],
  [ "🍭", "lollipop" ],
  [ "🍮", "custard" ],
  [ "🍯", "honey pot" ],
  [ "🍰", "shortcake" ],
  [ "🍱", "bento box" ],
  [ "🍲", "pot food" ],
  [ "🍳", "cooking" ],
  [ "🍴", "fork knife" ],
  [ "🍵", "teacup without handle" ],
  [ "🍶", "sake bottle cup" ],
  [ "🍷", "wine glass" ],
  [ "🍸", "cocktail glass" ],
  [ "🍹", "tropical drink" ],
  [ "🍺", "beer mug" ],
  [ "🍻", "clinking beer mugs" ],
  [ "🍼", "baby bottle" ],
  [ "🍽", "fork knife plate" ],
  [ "🍾", "bottle popping cork" ],
  [ "🍿", "popcorn" ],
  [ "🎀", "ribbon" ],
  [ "🎁", "wrapped present" ],
  [ "🎂", "birthday cake" ],
  [ "🎃", "jack o lantern" ],
  [ "🎄", "christmas tree" ],
  [ "🎅", "father christmas" ],
  [ "🎆", "fireworks" ],
  [ "🎇", "firework sparkler" ],
  [ "🎈", "balloon" ],
  [ "🎉", "party popper" ],
  [ "🎊", "confetti ball" ],
  [ "🎋", "tanabata tree" ],
  [ "🎌", "crossed flags" ],
  [ "🎍", "pine decoration" ],
  [ "🎎", "japanese dolls" ],
  [ "🎏", "carp streamer" ],
  [ "🎐", "wind chime" ],
  [ "🎑", "moon viewing ceremony" ],
  [ "🎒", "school satchel" ],
  [ "🎓", "graduation cap" ],
  [ "🎔", "heart tip on left" ],
  [ "🎕", "bouquet flowers" ],
  [ "🎖", "military medal" ],
  [ "🎗", "reminder ribbon" ],
  [ "🎘", "musical keyboard jacks" ],
  [ "🎙", "studio microphone" ],
  [ "🎚", "level slider" ],
  [ "🎛", "control knobs" ],
  [ "🎜", "beamed ascending musical notes" ],
  [ "🎝", "beamed descending musical notes" ],
  [ "🎞", "film frames" ],
  [ "🎟", "admission tickets" ],
  [ "🎠", "carousel horse" ],
  [ "🎡", "ferris wheel" ],
  [ "🎢", "roller coaster" ],
  [ "🎣", "fishing pole fish" ],
  [ "🎤", "microphone" ],
  [ "🎥", "movie camera" ],
  [ "🎦", "cinema" ],
  [ "🎧", "headphone" ],
  [ "🎨", "artist palette" ],
  [ "🎩", "top hat" ],
  [ "🎪", "circus tent" ],
  [ "🎫", "ticket" ],
  [ "🎬", "clapper board" ],
  [ "🎭", "performing arts" ],
  [ "🎮", "video game" ],
  [ "🎯", "direct hit" ],
  [ "🎰", "slot machine" ],
  [ "🎱", "billiards" ],
  [ "🎲", "game die" ],
  [ "🎳", "bowling" ],
  [ "🎴", "flower playing cards" ],
  [ "🎵", "musical note" ],
  [ "🎶", "multiple musical notes" ],
  [ "🎷", "saxophone" ],
  [ "🎸", "guitar" ],
  [ "🎹", "musical keyboard" ],
  [ "🎺", "trumpet" ],
  [ "🎻", "violin" ],
  [ "🎼", "musical score" ],
  [ "🎽", "running shirt sash" ],
  [ "🎾", "tennis racquet ball" ],
  [ "🎿", "ski boot" ],
  [ "🏀", "basketball hoop" ],
  [ "🏁", "chequered flag" ],
  [ "🏂", "snowboarder" ],
  [ "🏃", "runner" ],
  [ "🏄", "surfer" ],
  [ "🏅", "sports medal" ],
  [ "🏆", "trophy" ],
  [ "🏇", "horse racing" ],
  [ "🏈", "american football" ],
  [ "🏉", "rugby football" ],
  [ "🏊", "swimmer" ],
  [ "🏋", "weight lifter" ],
  [ "🏌", "golfer" ],
  [ "🏍", "racing motorcycle" ],
  [ "🏎", "racing car" ],
  [ "🏏", "cricket bat ball" ],
  [ "🏐", "volleyball" ],
  [ "🏑", "field hockey stick ball" ],
  [ "🏒", "ice hockey stick puck" ],
  [ "🏓", "table tennis paddle ball" ],
  [ "🏔", "snow capped mountain" ],
  [ "🏕", "camping" ],
  [ "🏖", "beach umbrella" ],
  [ "🏗", "building construction" ],
  [ "🏘", "house buildings" ],
  [ "🏙", "cityscape" ],
  [ "🏚", "derelict house building" ],
  [ "🏛", "classical building" ],
  [ "🏜", "desert" ],
  [ "🏝", "desert island" ],
  [ "🏞", "national park" ],
  [ "🏟", "stadium" ],
  [ "🏠", "house building" ],
  [ "🏡", "house garden" ],
  [ "🏢", "office building" ],
  [ "🏣", "japanese post office" ],
  [ "🏤", "european post office" ],
  [ "🏥", "hospital" ],
  [ "🏦", "bank" ],
  [ "🏧", "automated teller machine" ],
  [ "🏨", "hotel" ],
  [ "🏩", "love hotel" ],
  [ "🏪", "convenience store" ],
  [ "🏫", "school" ],
  [ "🏬", "department store" ],
  [ "🏭", "factory" ],
  [ "🏮", "izakaya lantern" ],
  [ "🏯", "japanese castle" ],
  [ "🏰", "european castle" ],
  [ "🏱", "white pennant" ],
  [ "🏲", "black pennant" ],
  [ "🏳", "waving white flag" ],
  [ "🏴", "waving black flag" ],
  [ "🏵", "rosette" ],
  [ "🏶", "black rosette" ],
  [ "🏷", "label" ],
  [ "🏸", "badminton racquet shuttlecock" ],
  [ "🏹", "bow arrow" ],
  [ "🏺", "amphora" ],
  [ "🐀", "rat" ],
  [ "🐁", "mouse" ],
  [ "🐂", "ox" ],
  [ "🐃", "water buffalo" ],
  [ "🐄", "cow" ],
  [ "🐅", "tiger" ],
  [ "🐆", "leopard" ],
  [ "🐇", "rabbit" ],
  [ "🐈", "cat" ],
  [ "🐉", "dragon" ],
  [ "🐊", "crocodile" ],
  [ "🐋", "whale" ],
  [ "🐌", "snail" ],
  [ "🐍", "snake" ],
  [ "🐎", "horse" ],
  [ "🐏", "ram" ],
  [ "🐐", "goat" ],
  [ "🐑", "sheep" ],
  [ "🐒", "monkey" ],
  [ "🐓", "rooster" ],
  [ "🐔", "chicken" ],
  [ "🐕", "dog" ],
  [ "🐖", "pig" ],
  [ "🐗", "boar" ],
  [ "🐘", "elephant" ],
  [ "🐙", "octopus" ],
  [ "🐚", "spiral shell" ],
  [ "🐛", "bug" ],
  [ "🐜", "ant" ],
  [ "🐝", "honeybee" ],
  [ "🐞", "lady beetle" ],
  [ "🐟", "fish" ],
  [ "🐠", "tropical fish" ],
  [ "🐡", "blowfish" ],
  [ "🐢", "turtle" ],
  [ "🐣", "hatching chick" ],
  [ "🐤", "baby chick" ],
  [ "🐥", "front facing baby chick" ],
  [ "🐦", "bird" ],
  [ "🐧", "penguin" ],
  [ "🐨", "koala" ],
  [ "🐩", "poodle" ],
  [ "🐪", "dromedary camel" ],
  [ "🐫", "bactrian camel" ],
  [ "🐬", "dolphin" ],
  [ "🐭", "mouse" ],
  [ "🐮", "cow" ],
  [ "🐯", "tiger" ],
  [ "🐰", "rabbit" ],
  [ "🐱", "cat" ],
  [ "🐲", "dragon" ],
  [ "🐳", "spouting whale" ],
  [ "🐴", "horse" ],
  [ "🐵", "monkey" ],
  [ "🐶", "dog" ],
  [ "🐷", "pig" ],
  [ "🐸", "frog" ],
  [ "🐹", "hamster" ],
  [ "🐺", "wolf" ],
  [ "🐻", "bear" ],
  [ "🐼", "panda" ],
  [ "🐽", "pig nose" ],
  [ "🐾", "paw prints" ],
  [ "🐿", "chipmunk" ],
  [ "👀", "eyes" ],
  [ "👁", "eye" ],
  [ "👂", "ear" ],
  [ "👃", "nose" ],
  [ "👄", "mouth" ],
  [ "👅", "tongue" ],
  [ "👆", "white up pointing backhand index" ],
  [ "👇", "white down pointing backhand index" ],
  [ "👈", "white left pointing backhand index" ],
  [ "👉", "white right pointing backhand index" ],
  [ "👊", "fisted hand" ],
  [ "👋", "waving hand" ],
  [ "👌", "ok hand" ],
  [ "👍", "thumbs up" ],
  [ "👎", "thumbs down" ],
  [ "👏", "clapping hands" ],
  [ "👐", "open hands" ],
  [ "👑", "crown" ],
  [ "👒", "womans hat" ],
  [ "👓", "eyeglasses" ],
  [ "👔", "necktie" ],
  [ "👕", "t shirt" ],
  [ "👖", "jeans" ],
  [ "👗", "dress" ],
  [ "👘", "kimono" ],
  [ "👙", "bikini" ],
  [ "👚", "womans clothes" ],
  [ "👛", "purse" ],
  [ "👜", "handbag" ],
  [ "👝", "pouch" ],
  [ "👞", "mans shoe" ],
  [ "👟", "athletic shoe" ],
  [ "👠", "high heeled shoe" ],
  [ "👡", "womans sandal" ],
  [ "👢", "womans boots" ],
  [ "👣", "footprints" ],
  [ "👤", "bust in silhouette" ],
  [ "👥", "busts in silhouette" ],
  [ "👦", "boy" ],
  [ "👧", "girl" ],
  [ "👨", "man" ],
  [ "👩", "woman" ],
  [ "👪", "family" ],
  [ "👫", "man woman holding hands" ],
  [ "👬", "two men holding hands" ],
  [ "👭", "two women holding hands" ],
  [ "👮", "police officer" ],
  [ "👯", "woman bunny ears" ],
  [ "👰", "bride veil" ],
  [ "👱", "person blond hair" ],
  [ "👲", "man gua pi mao" ],
  [ "👳", "man turban" ],
  [ "👴", "older man" ],
  [ "👵", "older woman" ],
  [ "👶", "baby" ],
  [ "👷", "construction worker" ],
  [ "👸", "princess" ],
  [ "👹", "japanese ogre" ],
  [ "👺", "japanese goblin" ],
  [ "👻", "ghost" ],
  [ "👼", "baby angel" ],
  [ "👽", "extraterrestrial alien" ],
  [ "👾", "alien monster" ],
  [ "👿", "imp" ],
  [ "💀", "skull" ],
  [ "💁", "information desk person" ],
  [ "💂", "guardsman" ],
  [ "💃", "dancer" ],
  [ "💄", "lipstick" ],
  [ "💅", "nail polish" ],
  [ "💆", "massage" ],
  [ "💇", "haircut" ],
  [ "💈", "barber pole" ],
  [ "💉", "syringe" ],
  [ "💊", "pill" ],
  [ "💋", "kiss mark" ],
  [ "💌", "love letter" ],
  [ "💍", "ring" ],
  [ "💎", "gem stone" ],
  [ "💏", "kiss" ],
  [ "💐", "bouquet" ],
  [ "💑", "couple heart" ],
  [ "💒", "wedding" ],
  [ "💓", "beating heart" ],
  [ "💔", "broken heart" ],
  [ "💕", "two hearts" ],
  [ "💖", "sparkling heart" ],
  [ "💗", "growing heart" ],
  [ "💘", "heart arrow" ],
  [ "💙", "blue heart" ],
  [ "💚", "green heart" ],
  [ "💛", "yellow heart" ],
  [ "💜", "purple heart" ],
  [ "💝", "heart ribbon" ],
  [ "💞", "revolving hearts" ],
  [ "💟", "heart decoration" ],
  [ "💠", "diamond shape dot inside" ],
  [ "💡", "electric light bulb" ],
  [ "💢", "anger" ],
  [ "💣", "bomb" ],
  [ "💤", "sleeping" ],
  [ "💥", "collision" ],
  [ "💦", "splashing sweat" ],
  [ "💧", "droplet" ],
  [ "💨", "dash" ],
  [ "💩", "pile poo" ],
  [ "💪", "flexed biceps" ],
  [ "💫", "dizzy" ],
  [ "💬", "speech balloon" ],
  [ "💭", "thought balloon" ],
  [ "💮", "white flower" ],
  [ "💯", "hundred points" ],
  [ "💰", "money bag" ],
  [ "💱", "currency exchange" ],
  [ "💲", "heavy dollar" ],
  [ "💳", "credit card" ],
  [ "💴", "banknote yen" ],
  [ "💵", "banknote dollar" ],
  [ "💶", "banknote euro" ],
  [ "💷", "banknote pound" ],
  [ "💸", "money wings" ],
  [ "💹", "chart upwards trend yen" ],
  [ "💺", "seat" ],
  [ "💻", "personal computer" ],
  [ "💼", "briefcase" ],
  [ "💽", "minidisc" ],
  [ "💾", "floppy disk" ],
  [ "💿", "optical disc" ],
  [ "📀", "dvd" ],
  [ "📁", "file folder" ],
  [ "📂", "open file folder" ],
  [ "📃", "page curl" ],
  [ "📄", "page facing up" ],
  [ "📅", "calendar" ],
  [ "📆", "tear off calendar" ],
  [ "📇", "card index" ],
  [ "📈", "chart upwards trend" ],
  [ "📉", "chart downwards trend" ],
  [ "📊", "bar chart" ],
  [ "📋", "clipboard" ],
  [ "📌", "pushpin" ],
  [ "📍", "round pushpin" ],
  [ "📎", "paperclip" ],
  [ "📏", "straight ruler" ],
  [ "📐", "triangular ruler" ],
  [ "📑", "bookmark tabs" ],
  [ "📒", "ledger" ],
  [ "📓", "notebook" ],
  [ "📔", "notebook decorative cover" ],
  [ "📕", "closed book" ],
  [ "📖", "open book" ],
  [ "📗", "green book" ],
  [ "📘", "blue book" ],
  [ "📙", "orange book" ],
  [ "📚", "books" ],
  [ "📛", "name badge" ],
  [ "📜", "scroll" ],
  [ "📝", "memo" ],
  [ "📞", "telephone receiver" ],
  [ "📟", "pager" ],
  [ "📠", "fax machine" ],
  [ "📡", "satellite antenna" ],
  [ "📢", "public address loudspeaker" ],
  [ "📣", "cheering megaphone" ],
  [ "📤", "outbox tray" ],
  [ "📥", "inbox tray" ],
  [ "📦", "package" ],
  [ "📧", "e mail" ],
  [ "📨", "incoming envelope" ],
  [ "📩", "envelope downwards arrow above" ],
  [ "📪", "closed mailbox lowered flag" ],
  [ "📫", "closed mailbox raised flag" ],
  [ "📬", "open mailbox raised flag" ],
  [ "📭", "open mailbox lowered flag" ],
  [ "📮", "postbox" ],
  [ "📯", "postal horn" ],
  [ "📰", "newspaper" ],
  [ "📱", "mobile phone" ],
  [ "📲", "mobile phone rightwards arrow at left" ],
  [ "📳", "vibration mode" ],
  [ "📴", "mobile phone off" ],
  [ "📵", "no mobile phones" ],
  [ "📶", "antenna bars" ],
  [ "📷", "camera" ],
  [ "📸", "camera flash" ],
  [ "📹", "video camera" ],
  [ "📺", "television" ],
  [ "📻", "radio" ],
  [ "📼", "videocassette" ],
  [ "📽", "film projector" ],
  [ "📾", "portable stereo" ],
  [ "📿", "prayer beads" ],
  [ "🔀", "twisted rightwards arrows" ],
  [ "🔁", "clockwise rightwards leftwards open circle arrows" ],
  [ "🔂", "clockwise rightwards leftwards open circle arrows circled one overlay" ],
  [ "🔃", "clockwise downwards upwards open circle arrows" ],
  [ "🔄", "anticlockwise downwards upwards open circle arrows" ],
  [ "🔅", "low brightness" ],
  [ "🔆", "high brightness" ],
  [ "🔇", "speaker cancellation stroke" ],
  [ "🔈", "speaker" ],
  [ "🔉", "speaker one sound wave" ],
  [ "🔊", "speaker three sound waves" ],
  [ "🔋", "battery" ],
  [ "🔌", "electric plug" ],
  [ "🔍", "left pointing magnifying glass" ],
  [ "🔎", "right pointing magnifying glass" ],
  [ "🔏", "lock ink pen" ],
  [ "🔐", "closed lock key" ],
  [ "🔑", "key" ],
  [ "🔒", "lock" ],
  [ "🔓", "open lock" ],
  [ "🔔", "bell" ],
  [ "🔕", "bell cancellation stroke" ],
  [ "🔖", "bookmark" ],
  [ "🔗", "link" ],
  [ "🔘", "radio button" ],
  [ "🔙", "back leftwards arrow above" ],
  [ "🔚", "end leftwards arrow above" ],
  [ "🔛", "on exclamation mark left right arrow above" ],
  [ "🔜", "soon rightwards arrow above" ],
  [ "🔝", "top upwards arrow above" ],
  [ "🔞", "no one under eighteen" ],
  [ "🔟", "keycap ten" ],
  [ "🔠", "input for latin capital letters" ],
  [ "🔡", "input for latin small letters" ],
  [ "🔢", "input for numbers" ],
  [ "🔣", "input for symbols" ],
  [ "🔤", "input for latin letters" ],
  [ "🔥", "fire" ],
  [ "🔦", "electric torch" ],
  [ "🔧", "wrench" ],
  [ "🔨", "hammer" ],
  [ "🔩", "nut bolt" ],
  [ "🔪", "hocho" ],
  [ "🔫", "pistol" ],
  [ "🔬", "microscope" ],
  [ "🔭", "telescope" ],
  [ "🔮", "crystal ball" ],
  [ "🔯", "six pointed star middle dot" ],
  [ "🔰", "japanese for beginner" ],
  [ "🔱", "trident emblem" ],
  [ "🔲", "black square button" ],
  [ "🔳", "white square button" ],
  [ "🔴", "large red circle" ],
  [ "🔵", "large blue circle" ],
  [ "🔶", "large orange diamond" ],
  [ "🔷", "large blue diamond" ],
  [ "🔸", "small orange diamond" ],
  [ "🔹", "small blue diamond" ],
  [ "🔺", "up pointing red triangle" ],
  [ "🔻", "down pointing red triangle" ],
  [ "🔼", "up pointing small red triangle" ],
  [ "🔽", "down pointing small red triangle" ],
  [ "🔾", "lower right shadowed white circle" ],
  [ "🔿", "upper right shadowed white circle" ],
  [ "🕀", "circled cross pommee" ],
  [ "🕁", "cross pommee half circle below" ],
  [ "🕂", "cross pommee" ],
  [ "🕃", "notched left semicircle three dots" ],
  [ "🕄", "notched right semicircle three dots" ],
  [ "🕅", "for marks chapter" ],
  [ "🕆", "white latin cross" ],
  [ "🕇", "heavy latin cross" ],
  [ "🕈", "celtic cross" ],
  [ "🕉", "om" ],
  [ "🕊", "dove peace" ],
  [ "🕋", "kaaba" ],
  [ "🕌", "mosque" ],
  [ "🕍", "synagogue" ],
  [ "🕎", "menorah nine branches" ],
  [ "🕏", "bowl hygieia" ],
  [ "🕐", "clock one oclock" ],
  [ "🕑", "clock two oclock" ],
  [ "🕒", "clock three oclock" ],
  [ "🕓", "clock four oclock" ],
  [ "🕔", "clock five oclock" ],
  [ "🕕", "clock six oclock" ],
  [ "🕖", "clock seven oclock" ],
  [ "🕗", "clock eight oclock" ],
  [ "🕘", "clock nine oclock" ],
  [ "🕙", "clock ten oclock" ],
  [ "🕚", "clock eleven oclock" ],
  [ "🕛", "clock twelve oclock" ],
  [ "🕜", "clock one thirty" ],
  [ "🕝", "clock two thirty" ],
  [ "🕞", "clock three thirty" ],
  [ "🕟", "clock four thirty" ],
  [ "🕠", "clock five thirty" ],
  [ "🕡", "clock six thirty" ],
  [ "🕢", "clock seven thirty" ],
  [ "🕣", "clock eight thirty" ],
  [ "🕤", "clock nine thirty" ],
  [ "🕥", "clock ten thirty" ],
  [ "🕦", "clock eleven thirty" ],
  [ "🕧", "clock twelve thirty" ],
  [ "🕨", "right speaker" ],
  [ "🕩", "right speaker one sound wave" ],
  [ "🕪", "right speaker three sound waves" ],
  [ "🕫", "bullhorn" ],
  [ "🕬", "bullhorn sound waves" ],
  [ "🕭", "ringing bell" ],
  [ "🕮", "book" ],
  [ "🕯", "candle" ],
  [ "🕰", "mantelpiece clock" ],
  [ "🕱", "black skull crossbones" ],
  [ "🕲", "no piracy" ],
  [ "🕳", "hole" ],
  [ "🕴", "man in business suit levitating" ],
  [ "🕵", "sleuth or spy" ],
  [ "🕶", "dark sunglasses" ],
  [ "🕷", "spider" ],
  [ "🕸", "spider web" ],
  [ "🕹", "joystick" ],
  [ "🕺", "man dancing" ],
  [ "🕻", "left hand telephone receiver" ],
  [ "🕼", "telephone receiver page" ],
  [ "🕽", "right hand telephone receiver" ],
  [ "🕾", "white touchtone telephone" ],
  [ "🕿", "black touchtone telephone" ],
  [ "🖀", "telephone on top modem" ],
  [ "🖁", "clamshell mobile phone" ],
  [ "🖂", "back envelope" ],
  [ "🖃", "stamped envelope" ],
  [ "🖄", "envelope lightning" ],
  [ "🖅", "flying envelope" ],
  [ "🖆", "pen over stamped envelope" ],
  [ "🖇", "linked paperclips" ],
  [ "🖈", "black pushpin" ],
  [ "🖉", "lower left pencil" ],
  [ "🖊", "lower left ballpoint pen" ],
  [ "🖋", "lower left fountain pen" ],
  [ "🖌", "lower left paintbrush" ],
  [ "🖍", "lower left crayon" ],
  [ "🖎", "left writing hand" ],
  [ "🖏", "turned ok hand" ],
  [ "🖐", "raised hand fingers splayed" ],
  [ "🖑", "reversed raised hand fingers splayed" ],
  [ "🖒", "reversed thumbs up" ],
  [ "🖓", "reversed thumbs down" ],
  [ "🖔", "reversed victory hand" ],
  [ "🖕", "reversed hand middle finger extended" ],
  [ "🖖", "raised hand part between middle ring fingers" ],
  [ "🖗", "white down pointing left hand index" ],
  [ "🖘", "sideways white left pointing index" ],
  [ "🖙", "sideways white right pointing index" ],
  [ "🖚", "sideways black left pointing index" ],
  [ "🖛", "sideways black right pointing index" ],
  [ "🖜", "black left pointing backhand index" ],
  [ "🖝", "black right pointing backhand index" ],
  [ "🖞", "sideways white up pointing index" ],
  [ "🖟", "sideways white down pointing index" ],
  [ "🖠", "sideways black up pointing index" ],
  [ "🖡", "sideways black down pointing index" ],
  [ "🖢", "black up pointing backhand index" ],
  [ "🖣", "black down pointing backhand index" ],
  [ "🖤", "black heart" ],
  [ "🖥", "desktop computer" ],
  [ "🖦", "keyboard mouse" ],
  [ "🖧", "three networked computers" ],
  [ "🖨", "printer" ],
  [ "🖩", "pocket calculator" ],
  [ "🖪", "black hard shell floppy disk" ],
  [ "🖫", "white hard shell floppy disk" ],
  [ "🖬", "soft shell floppy disk" ],
  [ "🖭", "tape cartridge" ],
  [ "🖮", "wired keyboard" ],
  [ "🖯", "one button mouse" ],
  [ "🖰", "two button mouse" ],
  [ "🖱", "three button mouse" ],
  [ "🖲", "trackball" ],
  [ "🖳", "old personal computer" ],
  [ "🖴", "hard disk" ],
  [ "🖵", "screen" ],
  [ "🖶", "printer icon" ],
  [ "🖷", "fax icon" ],
  [ "🖸", "optical disc icon" ],
  [ "🖹", "document text" ],
  [ "🖺", "document text picture" ],
  [ "🖻", "document picture" ],
  [ "🖼", "frame picture" ],
  [ "🖽", "frame tiles" ],
  [ "🖾", "frame an x" ],
  [ "🖿", "black folder" ],
  [ "🗀", "folder" ],
  [ "🗁", "open folder" ],
  [ "🗂", "card index dividers" ],
  [ "🗃", "card file box" ],
  [ "🗄", "file cabinet" ],
  [ "🗅", "empty note" ],
  [ "🗆", "empty note page" ],
  [ "🗇", "empty note pad" ],
  [ "🗈", "note" ],
  [ "🗉", "note page" ],
  [ "🗊", "note pad" ],
  [ "🗋", "empty document" ],
  [ "🗌", "empty page" ],
  [ "🗍", "empty pages" ],
  [ "🗎", "document" ],
  [ "🗏", "page" ],
  [ "🗐", "pages" ],
  [ "🗑", "wastebasket" ],
  [ "🗒", "spiral note pad" ],
  [ "🗓", "spiral calendar pad" ],
  [ "🗔", "desktop window" ],
  [ "🗕", "minimize" ],
  [ "🗖", "maximize" ],
  [ "🗗", "overlap" ],
  [ "🗘", "clockwise right left semicircle arrows" ],
  [ "🗙", "cancellation x" ],
  [ "🗚", "increase font size" ],
  [ "🗛", "decrease font size" ],
  [ "🗜", "compression" ],
  [ "🗝", "old key" ],
  [ "🗞", "rolled up newspaper" ],
  [ "🗟", "page circled text" ],
  [ "🗠", "stock chart" ],
  [ "🗡", "dagger knife" ],
  [ "🗢", "lips" ],
  [ "🗣", "speaking head in silhouette" ],
  [ "🗤", "three rays above" ],
  [ "🗥", "three rays below" ],
  [ "🗦", "three rays left" ],
  [ "🗧", "three rays right" ],
  [ "🗨", "left speech bubble" ],
  [ "🗩", "right speech bubble" ],
  [ "🗪", "two speech bubbles" ],
  [ "🗫", "three speech bubbles" ],
  [ "🗬", "left thought bubble" ],
  [ "🗭", "right thought bubble" ],
  [ "🗮", "left anger bubble" ],
  [ "🗯", "right anger bubble" ],
  [ "🗰", "mood bubble" ],
  [ "🗱", "lightning mood bubble" ],
  [ "🗲", "lightning mood" ],
  [ "🗳", "ballot box" ],
  [ "🗴", "ballot script x" ],
  [ "🗵", "ballot box script x" ],
  [ "🗶", "ballot bold script x" ],
  [ "🗷", "ballot box bold script x" ],
  [ "🗸", "light check mark" ],
  [ "🗹", "ballot box bold check" ],
  [ "🗺", "world map" ],
  [ "🗻", "mount fuji" ],
  [ "🗼", "tokyo tower" ],
  [ "🗽", "statue liberty" ],
  [ "🗾", "silhouette japan" ],
  [ "🗿", "moyai" ],
  [ "😀", "grinning" ],
  [ "😁", "grinning smiling eyes" ],
  [ "😂", "tears joy" ],
  [ "😃", "smiling open mouth" ],
  [ "😄", "smiling open mouth eyes" ],
  [ "😅", "smiling open mouth cold sweat" ],
  [ "😆", "smiling open mouth tightly closed eyes" ],
  [ "😇", "smiling halo" ],
  [ "😈", "smiling horns" ],
  [ "😉", "winking" ],
  [ "😊", "smiling eyes" ],
  [ "😋", "savouring delicious food" ],
  [ "😌", "relieved" ],
  [ "😍", "smiling heart shaped eyes" ],
  [ "😎", "smiling sunglasses" ],
  [ "😏", "smirking" ],
  [ "😐", "neutral" ],
  [ "😑", "expressionless" ],
  [ "😒", "unamused" ],
  [ "😓", "cold sweat" ],
  [ "😔", "pensive" ],
  [ "😕", "confused" ],
  [ "😖", "confounded" ],
  [ "😗", "kissing" ],
  [ "😘", "throwing kiss" ],
  [ "😙", "kissing smiling eyes" ],
  [ "😚", "kissing closed eyes" ],
  [ "😛", "stuck out tongue" ],
  [ "😜", "stuck out tongue winking eye" ],
  [ "😝", "stuck out tongue tightly closed eyes" ],
  [ "😞", "disappointed" ],
  [ "😟", "worried" ],
  [ "😠", "angry" ],
  [ "😡", "pouting" ],
  [ "😢", "crying" ],
  [ "😣", "persevering" ],
  [ "😤", "look triumph" ],
  [ "😥", "disappointed but relieved" ],
  [ "😦", "frowning open mouth" ],
  [ "😧", "anguished" ],
  [ "😨", "fearful" ],
  [ "😩", "weary" ],
  [ "😪", "sleepy" ],
  [ "😫", "tired" ],
  [ "😬", "grimacing" ],
  [ "😭", "loudly crying" ],
  [ "😮", "open mouth" ],
  [ "😯", "hushed" ],
  [ "😰", "open mouth cold sweat" ],
  [ "😱", "screaming in fear" ],
  [ "😲", "astonished" ],
  [ "😳", "flushed" ],
  [ "😴", "sleeping" ],
  [ "😵", "dizzy" ],
  [ "😶", "without mouth" ],
  [ "😷", "medical mask" ],
  [ "😸", "grinning cat smiling eyes" ],
  [ "😹", "cat tears joy" ],
  [ "😺", "smiling cat open mouth" ],
  [ "😻", "smiling cat heart shaped eyes" ],
  [ "😼", "cat wry smile" ],
  [ "😽", "kissing cat closed eyes" ],
  [ "😾", "pouting cat" ],
  [ "😿", "crying cat" ],
  [ "🙀", "weary cat" ],
  [ "🙁", "slightly frowning" ],
  [ "🙂", "slightly smiling" ],
  [ "🙃", "upside down" ],
  [ "🙄", "rolling eyes" ],
  [ "🙅", "no good gesture" ],
  [ "🙆", "ok gesture" ],
  [ "🙇", "person bowing deeply" ],
  [ "🙈", "see no evil monkey" ],
  [ "🙉", "hear no evil monkey" ],
  [ "🙊", "speak no evil monkey" ],
  [ "🙋", "happy person raising one hand" ],
  [ "🙌", "person raising both hands in celebration" ],
  [ "🙍", "person frowning" ],
  [ "🙎", "person pouting" ],
  [ "🙏", "person folded hands" ],
  [ "🚀", "rocket" ],
  [ "🚁", "helicopter" ],
  [ "🚂", "steam locomotive" ],
  [ "🚃", "railway car" ],
  [ "🚄", "high speed train" ],
  [ "🚅", "high speed train bullet nose" ],
  [ "🚆", "train" ],
  [ "🚇", "metro" ],
  [ "🚈", "light rail" ],
  [ "🚉", "station" ],
  [ "🚊", "tram" ],
  [ "🚋", "tram car" ],
  [ "🚌", "bus" ],
  [ "🚍", "oncoming bus" ],
  [ "🚎", "trolleybus" ],
  [ "🚏", "bus stop" ],
  [ "🚐", "minibus" ],
  [ "🚑", "ambulance" ],
  [ "🚒", "fire engine" ],
  [ "🚓", "police car" ],
  [ "🚔", "oncoming police car" ],
  [ "🚕", "taxi" ],
  [ "🚖", "oncoming taxi" ],
  [ "🚗", "automobile" ],
  [ "🚘", "oncoming automobile" ],
  [ "🚙", "recreational vehicle" ],
  [ "🚚", "delivery truck" ],
  [ "🚛", "articulated lorry" ],
  [ "🚜", "tractor" ],
  [ "🚝", "monorail" ],
  [ "🚞", "mountain railway" ],
  [ "🚟", "suspension railway" ],
  [ "🚠", "mountain cableway" ],
  [ "🚡", "aerial tramway" ],
  [ "🚢", "ship" ],
  [ "🚣", "rowboat" ],
  [ "🚤", "speedboat" ],
  [ "🚥", "horizontal traffic light" ],
  [ "🚦", "vertical traffic light" ],
  [ "🚧", "construction" ],
  [ "🚨", "police cars revolving light" ],
  [ "🚩", "triangular flag on post" ],
  [ "🚪", "door" ],
  [ "🚫", "no entry" ],
  [ "🚬", "smoking" ],
  [ "🚭", "no smoking" ],
  [ "🚮", "put litter in its place" ],
  [ "🚯", "do not litter" ],
  [ "🚰", "potable water" ],
  [ "🚱", "non potable water" ],
  [ "🚲", "bicycle" ],
  [ "🚳", "no bicycles" ],
  [ "🚴", "bicyclist" ],
  [ "🚵", "mountain bicyclist" ],
  [ "🚶", "pedestrian" ],
  [ "🚷", "no pedestrians" ],
  [ "🚸", "children crossing" ],
  [ "🚹", "mens" ],
  [ "🚺", "womens" ],
  [ "🚻", "restroom" ],
  [ "🚼", "baby" ],
  [ "🚽", "toilet" ],
  [ "🚾", "water closet" ],
  [ "🚿", "shower" ],
  [ "🛀", "bath" ],
  [ "🛁", "bathtub" ],
  [ "🛂", "passport control" ],
  [ "🛃", "customs" ],
  [ "🛄", "baggage claim" ],
  [ "🛅", "left luggage" ],
  [ "🛆", "triangle rounded corners" ],
  [ "🛇", "prohibited" ],
  [ "🛈", "circled information source" ],
  [ "🛉", "boys" ],
  [ "🛊", "girls" ],
  [ "🛋", "couch lamp" ],
  [ "🛌", "sleeping accommodation" ],
  [ "🛍", "shopping bags" ],
  [ "🛎", "bellhop bell" ],
  [ "🛏", "bed" ],
  [ "🛐", "place worship" ],
  [ "🛑", "octagonal" ],
  [ "🛒", "shopping trolley" ],
  [ "🛓", "stupa" ],
  [ "🛔", "pagoda" ],
  [ "🛕", "hindu temple" ],
  [ "🛖", "hut" ],
  [ "🛗", "elevator" ],
  [ "🛝", "playground slide" ],
  [ "🛞", "wheel" ],
  [ "🛟", "ring buoy" ],
  [ "🛠", "hammer wrench" ],
  [ "🛡", "shield" ],
  [ "🛢", "oil drum" ],
  [ "🛣", "motorway" ],
  [ "🛤", "railway track" ],
  [ "🛥", "motor boat" ],
  [ "🛦", "up pointing military airplane" ],
  [ "🛧", "up pointing airplane" ],
  [ "🛨", "up pointing small airplane" ],
  [ "🛩", "small airplane" ],
  [ "🛪", "northeast pointing airplane" ],
  [ "🛫", "airplane departure" ],
  [ "🛬", "airplane arriving" ],
  [ "🛰", "satellite" ],
  [ "🛱", "oncoming fire engine" ],
  [ "🛲", "diesel locomotive" ],
  [ "🛳", "passenger ship" ],
  [ "🛴", "scooter" ],
  [ "🛵", "motor scooter" ],
  [ "🛶", "canoe" ],
  [ "🛷", "sled" ],
  [ "🛸", "flying saucer" ],
  [ "🛹", "skateboard" ],
  [ "🛺", "auto rickshaw" ],
  [ "🛻", "pickup truck" ],
  [ "🛼", "roller skate" ],
  [ "🤀", "circled cross formee four dots" ],
  [ "🤁", "circled cross formee two dots" ],
  [ "🤂", "circled cross formee" ],
  [ "🤃", "left half circle four dots" ],
  [ "🤄", "left half circle three dots" ],
  [ "🤅", "left half circle two dots" ],
  [ "🤆", "left half circle dot" ],
  [ "🤇", "left half circle" ],
  [ "🤈", "downward facing hook" ],
  [ "🤉", "downward facing notched hook" ],
  [ "🤊", "downward facing hook dot" ],
  [ "🤋", "downward facing notched hook dot" ],
  [ "🤌", "pinched fingers" ],
  [ "🤍", "white heart" ],
  [ "🤎", "brown heart" ],
  [ "🤏", "pinching hand" ],
  [ "🤐", "zipper mouth" ],
  [ "🤑", "money mouth" ],
  [ "🤒", "thermometer" ],
  [ "🤓", "nerd" ],
  [ "🤔", "thinking" ],
  [ "🤕", "head bandage" ],
  [ "🤖", "robot" ],
  [ "🤗", "hugging" ],
  [ "🤘", "horns" ],
  [ "🤙", "call me hand" ],
  [ "🤚", "raised back hand" ],
  [ "🤛", "left facing fist" ],
  [ "🤜", "right facing fist" ],
  [ "🤝", "handshake" ],
  [ "🤞", "hand index middle fingers crossed" ],
  [ "🤟", "i love you hand" ],
  [ "🤠", "cowboy hat" ],
  [ "🤡", "clown" ],
  [ "🤢", "nauseated" ],
  [ "🤣", "rolling on floor laughing" ],
  [ "🤤", "drooling" ],
  [ "🤥", "lying" ],
  [ "🤦", "palm" ],
  [ "🤧", "sneezing" ],
  [ "🤨", "one eyebrow raised" ],
  [ "🤩", "grinning star eyes" ],
  [ "🤪", "grinning one large small eye" ],
  [ "🤫", "finger covering closed lips" ],
  [ "🤬", "serious symbols covering mouth" ],
  [ "🤭", "smiling eyes hand covering mouth" ],
  [ "🤮", "open mouth vomiting" ],
  [ "🤯", "shocked exploding head" ],
  [ "🤰", "pregnant woman" ],
  [ "🤱", "breast feeding" ],
  [ "🤲", "palms up together" ],
  [ "🤳", "selfie" ],
  [ "🤴", "prince" ],
  [ "🤵", "man in tuxedo" ],
  [ "🤶", "mother christmas" ],
  [ "🤷", "shrug" ],
  [ "🤸", "person doing cartwheel" ],
  [ "🤹", "juggling" ],
  [ "🤺", "fencer" ],
  [ "🤻", "modern pentathlon" ],
  [ "🤼", "wrestlers" ],
  [ "🤽", "water polo" ],
  [ "🤾", "handball" ],
  [ "🤿", "diving mask" ],
  [ "🥀", "wilted flower" ],
  [ "🥁", "drum drumsticks" ],
  [ "🥂", "clinking glasses" ],
  [ "🥃", "tumbler glass" ],
  [ "🥄", "spoon" ],
  [ "🥅", "goal net" ],
  [ "🥆", "rifle" ],
  [ "🥇", "first place medal" ],
  [ "🥈", "second place medal" ],
  [ "🥉", "third place medal" ],
  [ "🥊", "boxing glove" ],
  [ "🥋", "martial arts uniform" ],
  [ "🥌", "curling stone" ],
  [ "🥍", "lacrosse stick ball" ],
  [ "🥎", "softball" ],
  [ "🥏", "flying disc" ],
  [ "🥐", "croissant" ],
  [ "🥑", "avocado" ],
  [ "🥒", "cucumber" ],
  [ "🥓", "bacon" ],
  [ "🥔", "potato" ],
  [ "🥕", "carrot" ],
  [ "🥖", "baguette bread" ],
  [ "🥗", "green salad" ],
  [ "🥘", "shallow pan food" ],
  [ "🥙", "stuffed flatbread" ],
  [ "🥚", "egg" ],
  [ "🥛", "glass milk" ],
  [ "🥜", "peanuts" ],
  [ "🥝", "kiwifruit" ],
  [ "🥞", "pancakes" ],
  [ "🥟", "dumpling" ],
  [ "🥠", "fortune cookie" ],
  [ "🥡", "takeout box" ],
  [ "🥢", "chopsticks" ],
  [ "🥣", "bowl spoon" ],
  [ "🥤", "cup straw" ],
  [ "🥥", "coconut" ],
  [ "🥦", "broccoli" ],
  [ "🥧", "pie" ],
  [ "🥨", "pretzel" ],
  [ "🥩", "cut meat" ],
  [ "🥪", "sandwich" ],
  [ "🥫", "canned food" ],
  [ "🥬", "leafy green" ],
  [ "🥭", "mango" ],
  [ "🥮", "moon cake" ],
  [ "🥯", "bagel" ],
  [ "🥰", "smiling eyes three hearts" ],
  [ "🥱", "yawning" ],
  [ "🥲", "smiling tear" ],
  [ "🥳", "party horn hat" ],
  [ "🥴", "uneven eyes wavy mouth" ],
  [ "🥵", "overheated" ],
  [ "🥶", "freezing" ],
  [ "🥷", "ninja" ],
  [ "🥸", "disguised" ],
  [ "🥹", "holding back tears" ],
  [ "🥺", "pleading eyes" ],
  [ "🥻", "sari" ],
  [ "🥼", "lab coat" ],
  [ "🥽", "goggles" ],
  [ "🥾", "hiking boot" ],
  [ "🥿", "flat shoe" ],
  [ "🦀", "crab" ],
  [ "🦁", "lion" ],
  [ "🦂", "scorpion" ],
  [ "🦃", "turkey" ],
  [ "🦄", "unicorn" ],
  [ "🦅", "eagle" ],
  [ "🦆", "duck" ],
  [ "🦇", "bat" ],
  [ "🦈", "shark" ],
  [ "🦉", "owl" ],
  [ "🦊", "fox" ],
  [ "🦋", "butterfly" ],
  [ "🦌", "deer" ],
  [ "🦍", "gorilla" ],
  [ "🦎", "lizard" ],
  [ "🦏", "rhinoceros" ],
  [ "🦐", "shrimp" ],
  [ "🦑", "squid" ],
  [ "🦒", "giraffe" ],
  [ "🦓", "zebra" ],
  [ "🦔", "hedgehog" ],
  [ "🦕", "sauropod" ],
  [ "🦖", "t rex" ],
  [ "🦗", "cricket" ],
  [ "🦘", "kangaroo" ],
  [ "🦙", "llama" ],
  [ "🦚", "peacock" ],
  [ "🦛", "hippopotamus" ],
  [ "🦜", "parrot" ],
  [ "🦝", "raccoon" ],
  [ "🦞", "lobster" ],
  [ "🦟", "mosquito" ],
  [ "🦠", "microbe" ],
  [ "🦡", "badger" ],
  [ "🦢", "swan" ],
  [ "🦣", "mammoth" ],
  [ "🦤", "dodo" ],
  [ "🦥", "sloth" ],
  [ "🦦", "otter" ],
  [ "🦧", "orangutan" ],
  [ "🦨", "skunk" ],
  [ "🦩", "flamingo" ],
  [ "🦪", "oyster" ],
  [ "🦫", "beaver" ],
  [ "🦬", "bison" ],
  [ "🦭", "seal" ],
  [ "🦮", "guide dog" ],
  [ "🦯", "probing cane" ],
  [ "🦰", "emoji component red hair" ],
  [ "🦱", "emoji component curly hair" ],
  [ "🦲", "emoji component bald" ],
  [ "🦳", "emoji component white hair" ],
  [ "🦴", "bone" ],
  [ "🦵", "leg" ],
  [ "🦶", "foot" ],
  [ "🦷", "tooth" ],
  [ "🦸", "superhero" ],
  [ "🦹", "supervillain" ],
  [ "🦺", "safety vest" ],
  [ "🦻", "ear hearing aid" ],
  [ "🦼", "motorized wheelchair" ],
  [ "🦽", "manual wheelchair" ],
  [ "🦾", "mechanical arm" ],
  [ "🦿", "mechanical leg" ],
  [ "🧀", "cheese wedge" ],
  [ "🧁", "cupcake" ],
  [ "🧂", "salt shaker" ],
  [ "🧃", "beverage box" ],
  [ "🧄", "garlic" ],
  [ "🧅", "onion" ],
  [ "🧆", "falafel" ],
  [ "🧇", "waffle" ],
  [ "🧈", "butter" ],
  [ "🧉", "mate drink" ],
  [ "🧊", "ice cube" ],
  [ "🧋", "bubble tea" ],
  [ "🧌", "troll" ],
  [ "🧍", "standing person" ],
  [ "🧎", "kneeling person" ],
  [ "🧏", "deaf person" ],
  [ "🧐", "monocle" ],
  [ "🧑", "adult" ],
  [ "🧒", "child" ],
  [ "🧓", "older adult" ],
  [ "🧔", "bearded person" ],
  [ "🧕", "person headscarf" ],
  [ "🧖", "person in steamy room" ],
  [ "🧗", "person climbing" ],
  [ "🧘", "person in lotus position" ],
  [ "🧙", "mage" ],
  [ "🧚", "fairy" ],
  [ "🧛", "vampire" ],
  [ "🧜", "merperson" ],
  [ "🧝", "elf" ],
  [ "🧞", "genie" ],
  [ "🧟", "zombie" ],
  [ "🧠", "brain" ],
  [ "🧡", "orange heart" ],
  [ "🧢", "billed cap" ],
  [ "🧣", "scarf" ],
  [ "🧤", "gloves" ],
  [ "🧥", "coat" ],
  [ "🧦", "socks" ],
  [ "🧧", "red gift envelope" ],
  [ "🧨", "firecracker" ],
  [ "🧩", "jigsaw puzzle piece" ],
  [ "🧪", "test tube" ],
  [ "🧫", "petri dish" ],
  [ "🧬", "dna double helix" ],
  [ "🧭", "compass" ],
  [ "🧮", "abacus" ],
  [ "🧯", "fire extinguisher" ],
  [ "🧰", "toolbox" ],
  [ "🧱", "brick" ],
  [ "🧲", "magnet" ],
  [ "🧳", "luggage" ],
  [ "🧴", "lotion bottle" ],
  [ "🧵", "spool thread" ],
  [ "🧶", "ball yarn" ],
  [ "🧷", "safety pin" ],
  [ "🧸", "teddy bear" ],
  [ "🧹", "broom" ],
  [ "🧺", "basket" ],
  [ "🧻", "roll paper" ],
  [ "🧼", "bar soap" ],
  [ "🧽", "sponge" ],
  [ "🧾", "receipt" ],
  [ "🧿", "nazar amulet" ],
  [ "🩰", "ballet shoes" ],
  [ "🩱", "one piece swimsuit" ],
  [ "🩲", "briefs" ],
  [ "🩳", "shorts" ],
  [ "🩴", "thong sandal" ],
  [ "🩸", "drop blood" ],
  [ "🩹", "adhesive bandage" ],
  [ "🩺", "stethoscope" ],
  [ "🩻", "x ray" ],
  [ "🩼", "crutch" ],
  [ "🪀", "yo" ],
  [ "🪁", "kite" ],
  [ "🪂", "parachute" ],
  [ "🪃", "boomerang" ],
  [ "🪄", "magic wand" ],
  [ "🪅", "pinata" ],
  [ "🪆", "nesting dolls" ],
  [ "🪐", "ringed planet" ],
  [ "🪑", "chair" ],
  [ "🪒", "razor" ],
  [ "🪓", "axe" ],
  [ "🪔", "diya lamp" ],
  [ "🪕", "banjo" ],
  [ "🪖", "military helmet" ],
  [ "🪗", "accordion" ],
  [ "🪘", "long drum" ],
  [ "🪙", "coin" ],
  [ "🪚", "carpentry saw" ],
  [ "🪛", "screwdriver" ],
  [ "🪜", "ladder" ],
  [ "🪝", "hook" ],
  [ "🪞", "mirror" ],
  [ "🪟", "window" ],
  [ "🪠", "plunger" ],
  [ "🪡", "sewing needle" ],
  [ "🪢", "knot" ],
  [ "🪣", "bucket" ],
  [ "🪤", "mouse trap" ],
  [ "🪥", "toothbrush" ],
  [ "🪦", "headstone" ],
  [ "🪧", "placard" ],
  [ "🪨", "rock" ],
  [ "🪩", "mirror ball" ],
  [ "🪪", "identification card" ],
  [ "🪫", "low battery" ],
  [ "🪬", "hamsa" ],
  [ "🪰", "fly" ],
  [ "🪱", "worm" ],
  [ "🪲", "beetle" ],
  [ "🪳", "cockroach" ],
  [ "🪴", "potted plant" ],
  [ "🪵", "wood" ],
  [ "🪶", "feather" ],
  [ "🪷", "lotus" ],
  [ "🪸", "coral" ],
  [ "🪹", "empty nest" ],
  [ "🪺", "nest eggs" ],
  [ "🫀", "anatomical heart" ],
  [ "🫁", "lungs" ],
  [ "🫂", "people hugging" ],
  [ "🫃", "pregnant man" ],
  [ "🫄", "pregnant person" ],
  [ "🫅", "person crown" ],
  [ "🫐", "blueberries" ],
  [ "🫑", "bell pepper" ],
  [ "🫒", "olive" ],
  [ "🫓", "flatbread" ],
  [ "🫔", "tamale" ],
  [ "🫕", "fondue" ],
  [ "🫖", "teapot" ],
  [ "🫗", "pouring liquid" ],
  [ "🫘", "beans" ],
  [ "🫙", "jar" ],
  [ "🫠", "melting" ],
  [ "🫡", "saluting" ],
  [ "🫢", "open eyes hand over mouth" ],
  [ "🫣", "peeking eye" ],
  [ "🫤", "diagonal mouth" ],
  [ "🫥", "dotted line" ],
  [ "🫦", "biting lip" ],
  [ "🫧", "bubbles" ],
  [ "🫰", "hand index finger thumb crossed" ],
  [ "🫱", "rightwards hand" ],
  [ "🫲", "leftwards hand" ],
  [ "🫳", "palm down hand" ],
  [ "🫴", "palm up hand" ],
  [ "🫵", "index pointing at viewer" ],
  [ "🫶", "heart hands" ],
  [ "☀", "black sun rays" ],
  [ "☁", "cloud" ],
  [ "☂", "umbrella" ],
  [ "☃", "snowman" ],
  [ "☄", "comet" ],
  [ "★", "black star" ],
  [ "☆", "white star" ],
  [ "☎", "black telephone" ],
  [ "☑", "ballot box check" ],
  [ "☔", "umbrella rain drops" ],
  [ "☕", "hot beverage" ],
  [ "☘", "shamrock" ],
  [ "☠", "skull crossbones" ],
  [ "☢", "radioactive" ],
  [ "☣", "biohazard" ],
  [ "☦", "orthodox cross" ],
  [ "☪", "star crescent" ],
  [ "☮", "peace" ],
  [ "☯", "yin yang" ],
  [ "☸", "wheel dharma" ],
  [ "☹", "white frowning" ],
  [ "☺", "white smiling" ],
  [ "♈", "aries" ],
  [ "♉", "taurus" ],
  [ "♊", "gemini" ],
  [ "♋", "cancer" ],
  [ "♌", "leo" ],
  [ "♍", "virgo" ],
  [ "♎", "libra" ],
  [ "♏", "scorpius" ],
  [ "♐", "sagittarius" ],
  [ "♑", "capricorn" ],
  [ "♒", "aquarius" ],
  [ "♓", "pisces" ],
  [ "♟", "black chess pawn" ],
  [ "♠", "black spade suit" ],
  [ "♣", "black club suit" ],
  [ "♥", "black heart suit" ],
  [ "♦", "black diamond suit" ],
  [ "♨", "hot springs" ],
  [ "♻", "black universal recycling" ],
  [ "♾", "permanent paper" ],
  [ "♿", "wheelchair" ],
  [ "⚒", "hammer pick" ],
  [ "⚓", "anchor" ],
  [ "⚔", "crossed swords" ],
  [ "⚕", "staff aesculapius" ],
  [ "⚖", "scales" ],
  [ "⚗", "alembic" ],
  [ "⚙", "gear" ],
  [ "⚛", "atom" ],
  [ "⚜", "fleur de lis" ],
  [ "⚠", "warning" ],
  [ "⚡", "high voltage" ],
  [ "⚧", "male stroke female" ],
  [ "⚪", "medium white circle" ],
  [ "⚫", "medium black circle" ],
  [ "⚰", "coffin" ],
  [ "⚱", "funeral urn" ],
  [ "⚽", "soccer ball" ],
  [ "⚾", "baseball" ],
  [ "⛄", "snowman without snow" ],
  [ "⛅", "sun behind cloud" ],
  [ "⛈", "thunder cloud rain" ],
  [ "⛎", "ophiuchus" ],
  [ "⛏", "pick" ],
  [ "⛑", "helmet white cross" ],
  [ "⛓", "chains" ],
  [ "⛔", "no entry" ],
  [ "⛩", "shinto shrine" ],
  [ "⛪", "church" ],
  [ "⛰", "mountain" ],
  [ "⛱", "umbrella on ground" ],
  [ "⛲", "fountain" ],
  [ "⛳", "flag in hole" ],
  [ "⛴", "ferry" ],
  [ "⛵", "sailboat" ],
  [ "⛺", "tent" ],
  [ "⛽", "fuel pump" ],
  [ "✂", "black scissors" ],
  [ "✅", "white heavy check mark" ],
  [ "✈", "airplane" ],
  [ "✉", "envelope" ],
  [ "✊", "raised fist" ],
  [ "✋", "raised hand" ],
  [ "✌", "victory hand" ],
  [ "✍", "writing hand" ],
  [ "✏", "pencil" ],
  [ "✒", "black nib" ],
  [ "✔", "heavy check mark" ],
  [ "✖", "heavy multiplication x" ],
  [ "✝", "latin cross" ],
  [ "✡", "star david" ],
  [ "✨", "sparkles" ],
  [ "✳", "eight spoked asterisk" ],
  [ "✴", "eight pointed black star" ],
  [ "❄", "snowflake" ],
  [ "❇", "sparkle" ],
  [ "❌", "cross mark" ],
  [ "❎", "negative squared cross mark" ],
  [ "❓", "black question mark ornament" ],
  [ "❔", "white question mark ornament" ],
  [ "❕", "white exclamation mark ornament" ],
  [ "❗", "heavy exclamation mark" ],
  [ "❣", "heavy heart exclamation mark ornament" ],
  [ "❤", "heavy black heart" ],
  [ "➕", "heavy plus" ],
  [ "➖", "heavy minus" ],
  [ "➗", "heavy division" ],
  [ "➡", "black rightwards arrow" ]
]

// Curated first, so the emoji people actually pick outrank the long tail — but
// with the two tiers' terms MERGED where they overlap, not deduped. Dropping
// the Unicode row for an already-curated glyph made curated emoji HARDER to
// find than the rest: 🚀 is described as "launch startup business grow", so
// discarding its Unicode row meant searching "rocket" found nothing.
export const ALL_EMOJI = (() => {
  const terms = new Map()
  const push = ([ emoji, t ]) => terms.set(emoji, terms.has(emoji) ? `${terms.get(emoji)} ${t}` : t)
  EMOJI_CATEGORIES.flatMap(c => c.emoji).forEach(push)
  const curatedOrder = [ ...terms.keys() ]
  UNICODE_EMOJI.forEach(push)
  const rest = [ ...terms.keys() ].filter(e => !curatedOrder.includes(e))
  return [ ...curatedOrder, ...rest ].map(e => [ e, terms.get(e) ])
})()

// A grid this long is a scroll, not a choice — and the best matches are at the
// top by construction, so anything past this is noise.
const MAX_RESULTS = 120

// Every query word must match the START of some term word. Prefix rather than
// raw substring: `includes` made "art" match "heart" and "car" match "postcard",
// which is how a search for a specific thing came back full of unrelated ones.
function matches(terms, words) {
  const termWords = terms.split(" ")
  return words.every(w => termWords.some(t => t.startsWith(w)))
}

export function searchEmoji(query) {
  const q = String(query ?? "").trim().toLowerCase()
  if (!q) return []
  const words = q.split(/\s+/)

  const exact = []
  const prefix = []
  for (const [ emoji, terms ] of ALL_EMOJI) {
    if (!matches(terms, words)) continue
    // A whole-word hit is a better answer than a prefix one: searching "cat"
    // should lead with the cat, not the caterpillar.
    const termWords = terms.split(" ")
    ;(words.every(w => termWords.includes(w)) ? exact : prefix).push(emoji)
    if (exact.length >= MAX_RESULTS) break
  }
  return [ ...exact, ...prefix ].slice(0, MAX_RESULTS)
}
