"""Strip the emailable one-pager down to a Webflow rebuild kit.

The shipped file is one 583KB document because it has to survive being emailed
and opened from a desktop: fonts, images and the offline fallback deck are all
base64'd into it. None of that earns its place on a hosted marketing page, so
this pulls the three apart:

    assets/            every payload as a real file, for Webflow's asset panel
    styles.css         the stylesheet, minus the fonts and the fallback deck
    index.html         a reference build of the PUBLIC page — same design, copy
                       rewritten off the named client
    embed-verto-demo.html   the one part Webflow can't draw: the device mockup
                       with the live Verto, sized for an HTML Embed element

Everything is extracted by anchor or by CSS selector, never by line number —
the source is regenerated by build_research.py and its line numbers move.
"""

import base64, os, re, shutil

SRC = "/home/user/Survey-POC/public/verto-for-research.html"
OUT = "/home/user/Survey-POC/webflow"
ASSETS = OUT + "/assets"

src = open(SRC).read()
# Only what this script generates. rmtree(OUT) took the README and this file
# with it, which is a rude thing for a build to do to its own directory.
GENERATED = ("index.html", "styles.css", "webflow-1-head-css.html",
             "webflow-2-embed-markup.html", "webflow-3-body-js.html")
shutil.rmtree(ASSETS, ignore_errors=True)
os.makedirs(ASSETS)
for f in GENERATED:
    if os.path.exists(f"{OUT}/{f}"):
        os.remove(f"{OUT}/{f}")

# ---------------------------------------------------------------- assets ----
# Named in file order. The names are the contract between styles.css, the embed
# and Webflow's asset panel, so they're written down rather than derived from an
# index that would silently re-point every reference if a payload were added.
NAMES = [
    ("font/woff2", "overpass-400-700"),
    ("font/woff2", "poppins-600"),
    ("font/woff2", "poppins-700"),
    ("image/webp", "logo-playverto-white"),
    ("image/webp", "phone-verto-card"),
    ("image/webp", "laptop-screen-verto"),
    ("image/webp", "laptop-bezel"),
    ("image/webp", "results-world-map"),
    ("image/webp", "results-questions"),
    ("image/webp", "traction-figures"),
    ("image/webp", "logo-playverto-black"),
    ("image/webp", "fallback-card-1"),
    ("image/webp", "fallback-card-2"),
    ("image/webp", "fallback-card-3"),
]
# The fallback deck's art goes with the deck; the fonts are on Google Fonts,
# which Webflow supports natively and a CDN serves better than we can.
SKIP = {"fallback-card-1", "fallback-card-2", "fallback-card-3"}
FONTS = {"overpass-400-700", "poppins-600", "poppins-700"}

hits = list(re.finditer(r"data:(image/webp|font/woff2);base64,([A-Za-z0-9+/=]+)", src))
assert len(hits) == len(NAMES), f"{len(hits)} payloads but {len(NAMES)} names"

written = []
for h, (kind, name) in zip(hits, NAMES):
    assert h.group(1) == kind, f"{name}: expected {kind}, found {h.group(1)}"
    if name in SKIP or name in FONTS:
        continue
    ext = "woff2" if kind.startswith("font") else "webp"
    blob = base64.b64decode(h.group(2))
    open(f"{ASSETS}/{name}.{ext}", "wb").write(blob)
    written.append((f"{name}.{ext}", len(blob)))

# Every payload becomes a bare filename, so the rest of this script works on
# text rather than on megabytes of base64.
_it = iter(NAMES)
flat = re.sub(r"data:(?:image/webp|font/woff2);base64,[A-Za-z0-9+/=]+",
              lambda m: next(_it)[1] + (".woff2" if m.group(0).startswith("data:font") else ".webp"),
              src)

# ------------------------------------------------------------------ CSS ----
style = flat[flat.index("<style>") + 7:flat.index("</style>")]


def split_rules(css):
    """Top-level rules, each as (selector, whole_text). @media keeps its block."""
    out, i, depth, start = [], 0, 0, 0
    while i < len(css):
        c = css[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                chunk = css[start:i + 1]
                # The selector is reported with comments stripped. A rule
                # preceded by a banner comment otherwise reports a "selector"
                # starting with /* — so `@media` blocks weren't recognised as
                # such, and were kept whole with their dead rules inside.
                sel = re.sub(r"/\*.*?\*/", "", chunk[:chunk.index("{")], flags=re.S).strip()
                out.append((sel, chunk))
                start = i + 1
        i += 1
    tail = css[start:].strip()
    if tail:
        out.append(("", css[start:]))
    return out


rules = split_rules(style)
assert len(rules) > 100, f"CSS parse produced only {len(rules)} rules"

# The offline fallback deck. It exists so an emailed copy still shows something
# when the embed can't reach the network; a hosted page is already online, and
# if the player is unreachable the screenshot plus the full-screen link says the
# same thing for none of the weight.
DECK = re.compile(r"\.vd\b|\.vd-|@keyframes vd")


def drop_deck(text):
    """Strip .vd rules, including the ones nested inside @media blocks."""
    kept = []
    for sel, chunk in split_rules(text):
        if sel.startswith("@media") or sel.startswith("@supports"):
            head, inner = chunk[:chunk.index("{") + 1], chunk[chunk.index("{") + 1:chunk.rindex("}")]
            inner = drop_deck(inner)
            if inner.strip():
                kept.append(head + inner + "}")
            continue
        if DECK.search(sel):
            continue
        kept.append(chunk)
    return "".join(kept)


css = drop_deck(style)

# Rules for the chrome we just removed. Left in, they'd be dead weight in a
# handover kit and — worse — actively confusing: someone would style a
# .topbar in Webflow and wonder why two sets of rules fought over it.
DEAD = re.compile(r"\.topbar|nav\.sidenav|\.nav-link|\.nav-label|\.prepared-for|"
                  r"\.theme-toggle|\.logo\b|(?:^|[\s,>])footer\b")


def drop_chrome(text):
    """Drop dead selectors. Multi-selector rules keep the selectors still live —
    `.shell, main, nav.sidenav{ min-width: 0 }` must keep its first two."""
    kept = []
    for sel, chunk in split_rules(text):
        if sel.startswith("@media") or sel.startswith("@supports"):
            head, inner = chunk[:chunk.index("{") + 1], chunk[chunk.index("{") + 1:chunk.rindex("}")]
            inner = drop_chrome(inner)
            if inner.strip():
                kept.append(head + inner + "}")
            continue
        if not sel or sel.startswith("@") or sel.startswith(":root"):
            kept.append(chunk)
            continue
        live = [p for p in (p.strip() for p in sel.split(",")) if p and not DEAD.search(p)]
        if not live:
            continue
        if len(live) == len([p for p in sel.split(",") if p.strip()]):
            kept.append(chunk)
        else:
            cut = chunk.index("{")
            head, body = chunk[:cut], chunk[cut:]
            kept.append(head.replace(head.strip().split("*/")[-1].strip() or head.strip(),
                                     ", ".join(live)) + body)
    return "".join(kept)


css = drop_chrome(css)


def all_selectors(text):
    out = []
    for sel, chunk in split_rules(text):
        if sel.startswith("@media") or sel.startswith("@supports"):
            out += all_selectors(chunk[chunk.index("{") + 1:chunk.rindex("}")])
        elif sel:
            out += [p.strip() for p in sel.split(",")]
    return out


# Checked against parsed selectors, not raw text: prose in a comment mentioning
# a class is not a rule, and asserting on the raw string can't tell them apart.
survivors = [x for x in all_selectors(css) if DEAD.search(x)]
assert not survivors, f"chrome rules survived: {survivors[:5]}"

# Instructions for retargeting the emailed one-pager at another firm. True
# there, meaningless here — this build has no top bar and no client's name in
# it, and the pointers would send someone hunting for elements that are gone.
css = re.sub(r"/\* Styled for Strategic Analytics\..*?\*/\n", "", css, count=1, flags=re.S)
assert "MattersGraph" not in css, "the retarget note survived"

# The shell was a two-column grid: side nav, then main. With the nav gone main
# would land in the nav's 240px column and the whole page would render inside
# it — which is exactly what the first build did.
css, n = re.subn(r"(\.shell\{[^}]*?grid-template-columns:\s*)240px 1fr", r"\g<1>1fr", css, count=1)
assert n == 1, "couldn't collapse .shell to one column"

# And main was only ever flush-left because the nav sat to its left. It has to
# centre now — but NOT via `margin: 0 auto` on main: auto margins make a grid
# item shrink-to-fit, so main sized itself to its widest child (the 620px
# screenshot) and the page overflowed a phone by 278px. Narrowing the shell to
# main's own width centres it and leaves main stretching to fill the column.
css, n = re.subn(r"(\.shell\{[^}]*?max-width:\s*)1280px", r"\g<1>880px", css, count=1)
assert n == 1, "couldn't narrow .shell"

# The @font-face rules pointed at payloads we deliberately didn't write out.
css = re.sub(r"@font-face\{[^}]*\}", "", css)
css = re.sub(r"\n{3,}", "\n\n", css).strip()

GOOGLE_FONTS = """/* Fonts: Overpass and Poppins are both on Google Fonts, so Webflow can serve
   them natively (Site settings -> Fonts -> Google Fonts). The one-pager
   embedded them only because an emailed file has no network to fetch from.
   If you'd rather link them by hand, this is the pair the design uses:
   <link href="https://fonts.googleapis.com/css2?family=Overpass:wght@400..700&family=Poppins:wght@600;700&display=swap" rel="stylesheet"> */

"""
open(OUT + "/styles.css", "w").write(GOOGLE_FONTS + css + "\n")

# --------------------------------------------------------------- markup ----
body = flat[flat.index("<body"):flat.index("<script>")]
body = body[body.index(">") + 1:]


def rep(label, old, new, text):
    assert old in text, "NOT FOUND: " + label
    return text.replace(old, new, 1)


# Chrome Webflow already draws. A page inside their site inherits the site's
# header, nav and footer; shipping ours too would put two of each on the screen.
body = re.sub(r'<div class="topbar">.*?</div>\n</div>\n', "", body, count=1, flags=re.S)
body = re.sub(r'  <nav class="sidenav".*?</nav>\n', "", body, count=1, flags=re.S)
body = re.sub(r"<footer>.*?</footer>", "", body, count=1, flags=re.S)
for gone in ("topbar", "sidenav", "<footer>"):
    assert gone not in body, f"{gone} survived the strip"

# Copy: this was addressed to one firm by name. A public page can't be.
body = rep("eyebrow", "VertoNow · A proposal for Strategic Analytics",
           "VertoNow · The research platform", body)
body = rep("hero sub",
           "Your 100–150 primary interviews stay exactly as they are — the same list simply gets a second way in, one that takes three minutes and needs no diary.",
           "Your primary interviews stay exactly as they are — the same list simply gets a second way in, one that takes three minutes and needs no diary.",
           body)
body = rep("hero cta", '<a href="#start" class="btn btn-ghost">The proposal</a>',
           '<a href="#start" class="btn btn-ghost">How it works</a>', body)
# The pill row under the hero listed the client's own coverage sectors.
body = re.sub(r'    <div class="pill-row">\n(?:      <span>[^<]*</span>\n)+    </div>\n\n    <section id="try">',
              '    <section id="try">', body, count=1)
assert body.count('class="pill-row"') == 1, "wrong number of pill rows left"

body = rep("try copy", "embedded in this document", "embedded in this page", body)
body = rep("section 04 index", "04 — The Proposal", "04 — Getting Started", body)
body = rep("lede", 'VertoNow is a self-serve platform: <span class="firm">Strategic Analytics</span> owns the Verto, the brand on it, and the data behind it.',
           "VertoNow is a self-serve platform: you own the Verto, the brand on it, and the data behind it.", body)
# A public page wants a form, not a named person's inbox on a page crawlers
# read — this becomes an anchor for Webflow's own.
body = rep("cta link", 'href="mailto:michael@playverto.com?subject=VertoNow%20for%20Strategic%20Analytics"',
           'href="#contact"', body)
body = rep("cta label", "Get started with Michael →", "Talk to us about your list →", body)
assert "Strategic Analytics" not in body, "the client is still named in the markup"
assert "%%" not in body, "a doubled escape survived"

# The device mockup moves to the embed file, so the reference page marks the
# spot Webflow will put the HTML Embed element in.
mock = re.search(r'      <div class="try-intro">.*?<p class="demo-note".*?</p>\n', body, re.S)
assert mock, "couldn't find the device mockup block"
mockup_markup = mock.group(0)
body = body.replace(mockup_markup,
                    "      <!-- WEBFLOW: HTML Embed element goes here — paste embed-verto-demo.html -->\n"
                    '      <div id="verto-demo-embed"></div>\n')

# ------------------------------------------------------------- the embed ----
script = flat[flat.index("<script>") + 8:flat.index("</script>")]


def js(name, kind="function"):
    """One top-level declaration, by name, brace-matched."""
    pat = rf"\n  (?:// [^\n]*\n  )*{'function ' if kind == 'function' else 'const '}{name}\b"
    m = re.search(pat, script)
    assert m, "JS not found: " + name
    i = script.index(name, m.start())
    if kind == "const" and "{" not in script[i:script.index("\n", i)]:
        return script[m.start():script.index("\n", i)] + "\n"
    depth, j = 0, script.index("{", i)
    while True:
        if script[j] == "{":
            depth += 1
        elif script[j] == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
    return script[m.start():j + 1] + "\n"


DEMO_URL = re.search(r'const DEMO_PATH\s*=\s*"([^"]+)"', script).group(1)
ORIGIN = re.search(r'const DEMO_ORIGIN\s*=\s*"([^"]+)"', script).group(1)

embed_css = "".join(chunk for sel, chunk in split_rules(css) if not sel.startswith("@")
                    and re.search(r"laptop-mockup|laptop-frame|screen-shot|screen-embed|device-overlay|"
                                  r"laptop-overlay|phone-mockup|phone-screen-embed|phone-caption|"
                                  r"demo-note|try-intro", sel))
embed_media = "".join(chunk for sel, chunk in split_rules(css) if sel.startswith("@media")
                      and re.search(r"laptop-mockup|screen-embed|phone-mockup|try-intro|phone-screen-embed", chunk))

EMBED = """<!-- VertoNow live demo — paste into a Webflow HTML Embed element.
     Needs: the four images below uploaded to Webflow assets, and this page's
     domain added to the player's frame-ancestors (see README).
     Replace ASSET_BASE with the folder Webflow serves your uploads from. -->
<style>
%(css)s
%(media)s
</style>

<div class="try-intro">
  <div class="try-intro-copy">
    <p>A live Verto, embedded in this page — not a video of one.
       <span class="on-desktop">Play it in the laptop, or tap the phone to move it across.</span>
       <span class="on-mobile">Play it right here.</span></p>
  </div>
  <figure class="phone-mockup" id="phoneMockup">
    <button type="button" class="device-overlay" id="phonePlayOverlay" hidden><span>&#9654; Play it here</span></button>
    <img src="ASSET_BASE/phone-verto-card.webp" alt="The same Verto on a phone: a stacked card with a photo up top, the question below, and tappable answer tiles.">
    <figcaption class="phone-caption">Where most of your<br>contacts will answer it.</figcaption>
  </figure>
</div>

<div class="laptop-mockup" id="demoMockup">
  <button type="button" class="device-overlay laptop-overlay" id="laptopPlayOverlay" hidden><span>&#9654; Bring it back to the laptop</span></button>
  <img class="screen-shot" src="ASSET_BASE/laptop-screen-verto.webp" alt="A live Verto being played: a question card with a photo panel, picture answer options, a running score and a Check answer button.">
  <img src="ASSET_BASE/laptop-bezel.webp" class="laptop-frame" alt="">
</div>
<p class="demo-note" id="demoNote">A real Verto, playing right here. Want the whole thing?
  <a href="%(url)s" class="demo-link" target="_blank" rel="noopener">Open it in a new tab &#8599;</a></p>

<script>
(function(){
  const DEMO_ORIGIN = "%(origin)s";
  const DEMO_PATH   = "%(path)s";
  const mockup = document.getElementById('demoMockup');
%(js)s
})();
</script>
"""

demo_js = "".join([
    js("SCREEN_W", "const"), js("EMBED_H", "const"),
    js("nudgeVideos"), js("fitEmbed"),
    js("phone", "const"), js("phoneOverlay", "const"), js("laptopOverlay", "const"),
    "  let embedFailed = false;\n  let nudger = null;\n",
    js("killFrames"), js("fitPhoneEmbed"), js("syncOverlays"), js("bootFrame"),
    js("activateDevice"),
    """
  phoneOverlay?.addEventListener('click', () => activateDevice('phone'));
  laptopOverlay?.addEventListener('click', () => activateDevice('laptop'));

  if ('ResizeObserver' in window) {
    const ro = new ResizeObserver(() => { fitEmbed(); fitPhoneEmbed(); });
    if (mockup) ro.observe(mockup);
    if (phone) ro.observe(phone);
  } else {
    window.addEventListener('resize', () => { fitEmbed(); fitPhoneEmbed(); });
  }

  activateDevice('laptop');
""",
])
# The fallback deck is gone, so its failure path has to say something else:
# the screenshot stays put and the full-screen link carries the reader out.
demo_js = demo_js.replace("        startRebuild();", """        const note = document.getElementById('demoNote');
        if (note) note.innerHTML = 'The live demo needs a connection. ' +
          '<a href="' + DEMO_ORIGIN + DEMO_PATH + '" class="demo-link" target="_blank" rel="noopener">Open the Verto in a new tab \\u2197</a>';""")
assert "startRebuild" not in demo_js, "the fallback deck is still referenced"

embed = EMBED % {"css": embed_css.strip(), "media": embed_media.strip(), "js": demo_js,
                 "origin": ORIGIN, "path": DEMO_URL, "url": ORIGIN + DEMO_URL}

# Webflow caps an HTML Embed element at 10,000 characters, and the whole demo is
# ~15,500. It splits along the seams Webflow already provides — page custom code
# has a separate budget for the head and for before </body> — which also puts
# the script after the markup it looks for, without a DOMContentLoaded wrapper.
_c = embed.index("<style>"), embed.index("</style>") + 8
_j = embed.index("<script>"), embed.index("</script>") + 9
part_css = embed[_c[0]:_c[1]]
part_js = embed[_j[0]:_j[1]]
part_markup = embed[_c[1]:_j[0]].strip()

HEAD = """<!-- VertoNow demo, 1 of 3 -> Page settings > Custom code > Inside <head> tag.
     Upload the four .webp files to Webflow assets first and replace ASSET_BASE
     in part 2 with the folder Webflow serves them from. -->
"""
MARKUP = """<!-- VertoNow demo, 2 of 3 -> an HTML Embed element on the canvas, placed
     where the mockup should appear in section 01. Replace ASSET_BASE with your
     Webflow asset folder. -->
"""
FOOT = """<!-- VertoNow demo, 3 of 3 -> Page settings > Custom code > Before </body> tag.
     It has to load after the markup above, which this placement guarantees. -->
"""
for name, text in (("webflow-1-head-css.html", HEAD + part_css),
                   ("webflow-2-embed-markup.html", MARKUP + part_markup),
                   ("webflow-3-body-js.html", FOOT + part_js)):
    assert len(text) < 10000, f"{name} is {len(text)} chars, over Webflow's 10,000"
    open(f"{OUT}/{name}", "w").write(text + "\n")
    print(f"{name:30} {len(text):5} chars")
print()

# ------------------------------------------------------------ reference ----
PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VertoNow — a research platform that runs alongside your calls</title>
<link href="https://fonts.googleapis.com/css2?family=Overpass:wght@400..700&family=Poppins:wght@600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css">
</head>
<body data-theme="light">
<div class="shell"><main>
%(body)s
</main></div>
%(embed)s
</body>
</html>
"""
page = PAGE % {"body": body.replace('<div class="shell">', "").replace("  <main>", "").replace("  </main>\n</div>", ""),
               "embed": ""}
# The reference build inlines the embed where Webflow will place it, so the
# page can actually be looked at rather than only read.
page = page.replace('      <!-- WEBFLOW: HTML Embed element goes here — paste embed-verto-demo.html -->\n      <div id="verto-demo-embed"></div>\n',
                    embed.replace("ASSET_BASE", "assets"))
page = page.replace('<link rel="stylesheet" href="styles.css">',
                    '<link rel="stylesheet" href="styles.css">')
page = re.sub(r'src="(?!http|assets)([\w-]+\.webp)"', r'src="assets/\1"', page)
open(OUT + "/index.html", "w").write(page)

print("assets:")
for n, s in written:
    print(f"   {n:28} {s // 1024:4} KB")
print(f"\nstyles.css            {len(css) // 1024:4} KB")
print(f"index.html            {len(page) // 1024:4} KB")
print(f"(one-piece embed would be {len(embed)} chars — hence the split above)")
print(f"\ntotal kit: {sum(s for _, s in written) // 1024} KB of assets + {(len(css) + len(page)) // 1024} KB of source"
      f"   (was {len(src) // 1024} KB in one file)")
